### PR TITLE
Add patch file for WFLY 10.1 with Weld 2.4.

### PR DESCRIPTION
**Pull request by manovotn**
Adding a version with Weld 2.4.

### CODE REVIEW

**Comment by mkouba** [comment]
Merged, thanks!

**Comment by gunnarmorling** [comment]
Hi @mkouba, do you have a pointer to the place where this patch file is added to the patch ZIP file you provide for download? I.e. I reckon you have some sort of script which takes this patch file, the JARs, module.xml etc. and creates a ZIP file with that. But I can't find it :) Thanks a lot!

**Comment by mkouba** [comment]
Hi @gunnarmorling, it's an official WildFly patch tool: https://github.com/jbossas/patch-gen

**Comment by gunnarmorling** [comment]
Thanks Martin! Do you invoke that tool manually or do you have some build
script which is using it?

**Comment by mkouba** [comment]
We only use this tool manually during the release process.

**Comment by gunnarmorling** [comment]
Ok, I feared you'd say that ;) But I got it working now, thanks!

**Pull request closed without merging**
